Hotfix - Ignore `<template>` when calculating grid items
markmead/alpinejs-masonry pull request #5
Opened 2024-01-21 20:04 UTC by ThatIsAPseudo

When using `x-masonry` on an element whose children items are generated through a `<template>` element, this `<template>` wasn't excluded from the `gridItems` array.  This led to alignment issues because of miscomputed margins.

(This change wasn't tested yet as I'm not familiar with the build process.)

2024-01-21 21:30 UTC, markmead requested changes
Happy to do the build stuff, just a few fixes.

2024-01-21 21:30 UTC, markmead commented on src/useMasonry.js
> +    (gridItem) => ((gridItem.nodeType === 1) and (gridItem.tagName != 'TEMPLATE'))
You can't write `and` in JavaScript, it would be `&&`.

2024-01-21 21:30 UTC, markmead commented on src/useMasonry.js
> +    (gridItem) => ((gridItem.nodeType === 1) and (gridItem.tagName != 'TEMPLATE'))
It should be using `!==` for extra strictness.

2024-01-22 06:32 UTC, ThatIsAPseudo commented on src/useMasonry.js
> +    (gridItem) => ((gridItem.nodeType === 1) and (gridItem.tagName != 'TEMPLATE'))
Thanks for pointing these out, I should've seen that.

2024-01-24 09:35 UTC, merged